permissions:
  packages: write
  contents: write

name: Build and Push Docker Images
on:
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:
  build-and-push-cloak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setting Cloak version
        run: |
          git clone https://github.com/cbeuw/Cloak.git
          cd Cloak
          CLOAK_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "CLOAK_VERSION=$CLOAK_VERSION"
          echo "CLOAK_VERSION=$CLOAK_VERSION" >> $GITHUB_ENV

      - name: Build and Publish Docker Cloak image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/$OWNER/$REPO/cloak-server"
          TAG="$IMAGE_NAME:"${{ env.CLOAK_VERSION }}
          docker build -f Dockerfile-cloak-server -t "$TAG.${{ github.run_number }}" -t "$IMAGE_NAME:latest" .
          docker push "$IMAGE_NAME" --all-tags
      
            
  build-and-push-awg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setting AWG version
        run: |
          git clone https://github.com/amnezia-vpn/amneziawg-go
          cd amneziawg-go
          AWG_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "AWG_VERSION=$AWG_VERSION"
          echo "AWG_VERSION=$AWG_VERSION" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.1'

      - name: Build and Publish Docker AWG image
        run: |
          cd amneziawg-go
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/$OWNER/$REPO/awg-server"
          TAG="$IMAGE_NAME:"${{ env.AWG_VERSION }}
          docker build -f Dockerfile -t "$TAG.${{ github.run_number }}" -t "$IMAGE_NAME:latest" .
          docker push "$IMAGE_NAME" --all-tags
